theme: jekyll-theme-minimal
title: Gregory C. Dwyer
logo: "/imgs/profile%20pic.jpg"
description: Nibbles and bytes of my projects.
background-image: "/HTML5/background.jpg"
social-network-links:
  email: "gregorydwyer@live.com"
