theme: jekyll-theme-minimal
title: Gregory Dwyer
avatar: ![logo](https://raw.githubusercontent.com/gregorydwyer/gregorydwyer.github.io/master/logo%20800px.png)
description: Tidbits and nibbles of the things that I do.
